### ISSUE TITLE
[Victory]Null Pointer Exception: After clicking on apply match for initial_fwd app

### ISSUE THREAD

**Issue by shub1989** [eMoflon/emoflon-victory#31]
After Running INITIAL_FWD_debug_app.java and getting matches, When we click on apply match for some matches it gives null pointer exception.
![Exception](https://user-images.githubusercontent.com/45486055/65530985-3f326100-def9-11e9-9c4f-4fdfb716ea23.jpg)

**Comment by Surbhi2111** [comment]
the same exception occurs even for  INITIAL_BWD_debug_app.java while doing apply match, and  when a protocol step(for empty/no match) is choosen.

**Comment by JaneJose** [comment]
@Surbhi2111 @shub1989  Can you please add the steps how to reproduce this issue as well as the stack trace of the exception? What is an empty match? With the models we tested it didn't occur yet.

**Comment by shub1989** [comment]
Steps to reproduce exception:
1) Run MODELGEN_App.java and get src.xmi for forward operation.
2)Then Run INITlAL_FWD_Debug_App.java for forward operation.
3)Once you get matches select any match and apply. For some matches it throws null pointer exception. This is only for some matches where we can't see any nodes or edges. The one who has, for them there is no exception. following is the stack trace for exception.



Exception occurred
java.lang.NullPointerException
	at org.emoflon.ibex.tgg.ui.debug.adapter.TGGAdpater.EObjectAdapter.constructGraphDomain(EObjectAdapter.java:98)
	at org.emoflon.ibex.tgg.ui.debug.adapter.TGGAdpater.IbexMatchAdapter.buildGraph(IbexMatchAdapter.java:95)
	at org.emoflon.ibex.tgg.ui.debug.adapter.TGGAdpater.IbexMatchAdapter.getGraph(IbexMatchAdapter.java:66)
	at org.emoflon.ibex.tgg.ui.debug.views.visualisable.MatchVisualisation.generateVisualisationString(MatchVisualisation.java:27)
	at org.emoflon.ibex.tgg.ui.debug.views.visualisable.VisualisableElement.refresh(VisualisableElement.java:32)
	at org.emoflon.ibex.tgg.ui.debug.views.visualisable.VisualisableElement.getImage(VisualisableElement.java:23)
	at org.emoflon.ibex.tgg.ui.debug.views.MatchDisplayView.refresh(MatchDisplayView.java:180)
	at org.emoflon.ibex.tgg.ui.debug.views.MatchDisplayView.display(MatchDisplayView.java:156)
	at org.emoflon.ibex.tgg.ui.debug.views.MatchListView$3.selectionChanged(MatchListView.java:109)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:158)
	at org.eclipse.jface.util.SafeRunnable$1.run(SafeRunnable.java:129)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:155)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2182)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1225)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetSelected(StructuredViewer.java:1254)
	at org.eclipse.jface.util.OpenStrategy.fireSelectionEvent(OpenStrategy.java:243)
	at org.eclipse.jface.util.OpenStrategy.access$4(OpenStrategy.java:238)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:403)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.emoflon.ibex.tgg.ui.debug.core.VictoryUI.run(VictoryUI.java:85)
	at org.emoflon.ibex.tgg.ui.debug.api.Victory.run(Victory.java:18)
	at org.emoflon.ibex.tgg.ui.debug.adapter.TGGAdpater.VictoryIBeXAdapter.runUI(VictoryIBeXAdapter.java:40)
	at org.emoflon.ibex.tgg.run.cheat1facebooktoinstagram.debug.INITIAL_FWD_Debug_App.main(INITIAL_FWD_Debug_App.java:56)

**Comment by Surbhi2111** [comment]
The similar steps need to be followed for Bwd_debug as well.

By empty match I meant, matches which do not further activate any other match (matches for which we dont get any nodes/edges )
So when we do apply match for such matches in any debugging option , the resulting protocol steps has no visualisation and when we select those Protocol steps(for visualisation) we get the exception.

**Comment by JaneJose** [comment]
Hi, in order to reproduce this issue, can you please give us the TGG you used and the order of rule applications you did until the exception was thrown (including the rule application that gave the error)?

**Comment by shub1989** [comment]
The TGG We used for testing debugger is Social Network Synchronization Example. When you start forward operation and start applying match from the  start, for some matches it gives null pointer exception. So, like shown in SS if you see,i did forward operation and then chose match with the id #0.14 and it throws exception. So this happens for some but not all matches. So if you want to know for exactly which match it gives exception, you need to do apply match for every single GEN file. Because, sometimes it may not give the exception for other matches.

**Comment by JaneJose** [comment]
We followed the exact steps as described but were not able to reproduce this issue.

**Comment by shub1989** [comment]
@JaneJose I tried updating the tool and still it is giving me the same exception. i am uploading a video for the same.
